name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: SumanChettri  # replace with your GitHub username
          outputs: dist, dist_static

      - name: Commit and Push
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: "chore: generate snake"
          add: "."
          push: true
