name: Update README with Blog Posts

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight (UTC)
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://your-blog-feed-url"   # Replace with your actual RSS feed URL

      # Optional: Add a debugging step to output log info
      - name: List README file
        run: ls -la README.md
